# Generated by Django 4.1.7 on 2023-05-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="businessProcesses",
            fields=[
                ("entryId", models.BigAutoField(primary_key=True, serialize=False)),
                ("processId", models.UUIDField()),
                ("name", models.CharField(max_length=254)),
                ("description", models.TextField()),
                ("owner", models.IntegerField()),
                ("dateCreated", models.DateField()),
                ("reviewDate", models.DateField()),
            ],
        ),
    ]
