# Generated by Django 4.1.7 on 2023-05-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="staffRole",
            fields=[
                (
                    "roleId",
                    models.UUIDField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("roleTitle", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=254)),
            ],
        ),
    ]
