# Generated by Django 4.1.7 on 2023-05-01 15:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0003_staff_jobtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="staffId",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="staffrole",
            name="roleId",
            field=models.UUIDField(
                auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
