# Generated by Django 4.1.7 on 2023-05-01 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0004_alter_staff_staffid_alter_staffrole_roleid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staff",
            old_name="surname",
            new_name="lastName",
        ),
    ]
