# Generated by Django 4.1.7 on 2023-05-01 16:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0005_rename_surname_staff_lastname"),
    ]

    operations = [
        migrations.CreateModel(
            name="assetsTypes",
            fields=[
                (
                    "assetId",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assetTypeName", models.CharField(max_length=100)),
                ("assetDTypeDescription", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="processes",
            fields=[
                (
                    "processId",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processName", models.CharField(max_length=100)),
                ("processDescription", models.CharField(max_length=254)),
                ("processAssets", models.CharField(max_length=254)),
                ("processOwner", models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="assets",
            fields=[
                (
                    "assetId",
                    models.UUIDField(
                        auto_created=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assetName", models.CharField(max_length=100)),
                ("assetDescription", models.CharField(max_length=254)),
                (
                    "assetOwner",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rifha.staff",
                    ),
                ),
                (
                    "assetType",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rifha.assetstypes",
                    ),
                ),
            ],
        ),
    ]
