# Generated by Django 4.1.7 on 2023-05-01 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0007_rename_contactnumber_staff_contactnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="assetId",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="assetstypes",
            name="assetId",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="processes",
            name="processId",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="staffId",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="staffrole",
            name="roleId",
            field=models.CharField(
                auto_created=True,
                default=uuid.uuid4,
                max_length=36,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
