# Generated by Django 4.1.7 on 2023-06-13 11:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0008_alter_assets_assetid_alter_assetstypes_assetid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="jobTitle",
        ),
    ]
