# Generated by Django 4.1.7 on 2023-06-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0010_staff_jobtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="active",
            field=models.IntegerField(default=1),
        ),
    ]
