# Generated by Django 4.1.7 on 2023-06-13 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0011_staff_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetstypes",
            old_name="assetDTypeDescription",
            new_name="assetTypeDescription",
        ),
    ]
