# Generated by Django 4.1.7 on 2023-06-14 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0012_rename_assetdtypedescription_assetstypes_assettypedescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="assetsClassifications",
            fields=[
                (
                    "classification_Id",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assetTypeName", models.CharField(max_length=100)),
                ("assetTypeDescription", models.CharField(max_length=254)),
            ],
        ),
    ]
