# Generated by Django 4.1.7 on 2023-06-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0013_assetsclassifications"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assetsclassifications",
            old_name="assetTypeName",
            new_name="classificationLabel",
        ),
        migrations.RemoveField(
            model_name="assetsclassifications",
            name="assetTypeDescription",
        ),
        migrations.AddField(
            model_name="assetsclassifications",
            name="classificationDescription",
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
    ]
