# Generated by Django 4.1.7 on 2023-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rifha",
            "0014_rename_assettypename_assetsclassifications_classificationlabel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assetsclassifications",
            name="rank",
            field=models.IntegerField(default=0),
        ),
    ]
