# Generated by Django 4.1.7 on 2023-06-14 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0015_assetsclassifications_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="assetClassification",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.assetsclassifications",
            ),
        ),
    ]
