# Generated by Django 4.1.7 on 2023-06-14 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0017_rename_assetid_assetstypes_assettypeid"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="fullName",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assets",
            name="assetId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
