# Generated by Django 4.1.7 on 2023-06-14 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0018_staff_fullname_alter_assets_assetid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="assetId",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
