# Generated by Django 4.1.7 on 2023-06-14 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0019_alter_assets_assetid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="assetClassification",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.assetsclassifications",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="assetType",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.assetstypes",
            ),
        ),
    ]
