# Generated by Django 4.1.7 on 2023-06-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0022_alter_assets_assetdescription_riskreg"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskreg",
            name="riskRef",
        ),
        migrations.AddField(
            model_name="riskreg",
            name="riskAsset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.assets",
            ),
        ),
        migrations.AddField(
            model_name="riskreg",
            name="riskNotes",
            field=models.TextField(default=None, max_length=2000),
            preserve_default=False,
        ),
    ]
