# Generated by Django 4.1.7 on 2023-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0023_remove_riskreg_riskref_riskreg_riskasset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="riskNotes",
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
