# Generated by Django 4.1.7 on 2023-06-15 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0024_alter_riskreg_risknotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="threatCatalogue",
            fields=[
                (
                    "threatId",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("threatlikelihood", models.FloatField()),
                (
                    "threatCategory",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rifha.staff",
                    ),
                ),
                (
                    "threatName",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rifha.assets",
                    ),
                ),
            ],
        ),
    ]
