# Generated by Django 4.1.7 on 2023-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0025_threatcatalogue"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatcatalogue",
            name="threatARO",
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatCategory",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatName",
            field=models.CharField(max_length=200),
        ),
    ]
