# Generated by Django 4.1.7 on 2023-06-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0026_threatcatalogue_threataro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskreg",
            name="riskThreats",
            field=models.CharField(
                default="a5eb6a73-22ca-450b-a6b8-c2273f994ef3", max_length=36
            ),
        ),
    ]
