# Generated by Django 4.1.7 on 2023-06-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0027_riskreg_riskthreats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="riskThreats",
            field=models.ForeignKey(
                default="a5eb6a73-22ca-450b-a6b8-c2273f994ef3",
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.threatcatalogue",
            ),
        ),
    ]
