# Generated by Django 4.1.7 on 2023-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0028_alter_riskreg_riskthreats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskreg",
            name="riskThreats",
        ),
        migrations.AddField(
            model_name="riskreg",
            name="riskThreats",
            field=models.ManyToManyField(to="rifha.threatcatalogue"),
        ),
    ]
