# Generated by Django 4.1.7 on 2023-06-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0029_remove_riskreg_riskthreats_riskreg_riskthreats"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskreg",
            name="riskRef",
            field=models.IntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
