# Generated by Django 4.1.7 on 2023-06-16 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0030_riskreg_riskref"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskreg",
            name="riskRef",
        ),
    ]
