# Generated by Django 4.1.7 on 2023-06-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0033_riskreg_riskcontrols"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskreg",
            name="analysisStatus",
            field=models.BooleanField(default=False, verbose_name="Analysis Completed"),
        ),
    ]
