# Generated by Django 4.1.7 on 2023-06-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0034_riskreg_analysisstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riskreg",
            old_name="analysisStatus",
            new_name="controlAnalysisStatus",
        ),
        migrations.AddField(
            model_name="riskreg",
            name="riskAnalysisStatus",
            field=models.BooleanField(default=False, verbose_name="Analysis Completed"),
        ),
    ]
