# Generated by Django 4.1.7 on 2023-06-23 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0035_rename_analysisstatus_riskreg_controlanalysisstatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="controlTypes",
            fields=[
                (
                    "controlTypeId",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("controlTypeName", models.CharField(max_length=100)),
                ("controlTypeDescription", models.CharField(max_length=254)),
            ],
        ),
    ]
