# Generated by Django 4.1.7 on 2023-06-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0036_controltypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controltypes",
            name="controlTypeDescription",
            field=models.CharField(max_length=2000),
        ),
    ]
