# Generated by Django 4.1.7 on 2023-06-23 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0037_alter_controltypes_controltypedescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlcatalogue",
            name="controlCategory",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.controltypes",
            ),
        ),
    ]
