# Generated by Django 4.1.7 on 2023-06-23 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0038_alter_controlcatalogue_controlcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controlcatalogue",
            name="controlCategory",
            field=models.ForeignKey(
                default="00545586-f865-48f5-9c33-19394977b783",
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.controltypes",
            ),
        ),
    ]
