# Generated by Django 4.1.7 on 2023-06-23 20:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0039_alter_controlcatalogue_controlcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="processCriticality",
            fields=[
                (
                    "processeId",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("processCriticality", models.CharField(max_length=100)),
                ("processCriticalityDescription", models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name="processes",
            old_name="processId",
            new_name="processeId",
        ),
        migrations.RemoveField(
            model_name="processes",
            name="processAssets",
        ),
        migrations.RemoveField(
            model_name="processes",
            name="processOwner",
        ),
        migrations.AlterField(
            model_name="processes",
            name="processDescription",
            field=models.CharField(max_length=2000),
        ),
        migrations.AddField(
            model_name="processes",
            name="processCriticality",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.processcriticality",
            ),
        ),
    ]
