# Generated by Django 4.1.7 on 2023-06-24 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0040_processcriticality_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="processcriticality",
            old_name="processeId",
            new_name="processeCriticalityId",
        ),
    ]
