# Generated by Django 4.1.7 on 2023-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rifha",
            "0042_rename_processecriticalityid_processcriticality_processcriticalityid_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="processcriticality",
            old_name="processCriticalityId",
            new_name="processeCriticalityId",
        ),
    ]
