# Generated by Django 4.1.7 on 2023-06-24 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rifha",
            "0043_rename_processcriticalityid_processcriticality_processecriticalityid",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="processcriticality",
            old_name="processeCriticalityId",
            new_name="processCriticalityId",
        ),
    ]
