# Generated by Django 4.1.7 on 2023-06-24 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "rifha",
            "0044_rename_processecriticalityid_processcriticality_processcriticalityid",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processes",
            name="processCriticality",
        ),
    ]
