# Generated by Django 4.1.7 on 2023-06-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0045_remove_processes_processcriticality"),
    ]

    operations = [
        migrations.DeleteModel(
            name="processCriticality",
        ),
        migrations.RenameField(
            model_name="processes",
            old_name="processeId",
            new_name="processId",
        ),
        migrations.AddField(
            model_name="processes",
            name="processAssets",
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processes",
            name="processOwner",
            field=models.CharField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processes",
            name="processDescription",
            field=models.CharField(max_length=254),
        ),
    ]
