# Generated by Django 4.1.7 on 2023-06-24 13:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0046_delete_processcriticality_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="businessProcessCriticality",
            fields=[
                (
                    "businessProcessCriticalityId",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("businessProcessCriticality", models.CharField(max_length=100)),
                (
                    "businessProcessCriticalityDescription",
                    models.CharField(max_length=2000),
                ),
            ],
        ),
        migrations.CreateModel(
            name="businessProcess",
            fields=[
                (
                    "businessProcessId",
                    models.CharField(
                        auto_created=True,
                        default=uuid.uuid4,
                        max_length=36,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("businessProcessName", models.CharField(max_length=100)),
                ("businessProcessDescription", models.CharField(max_length=2000)),
                (
                    "businessProcessCriticality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rifha.businessprocesscriticality",
                    ),
                ),
            ],
        ),
    ]
