# Generated by Django 4.1.7 on 2023-06-24 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0047_businessprocesscriticality_businessprocess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rifha.staff"
            ),
        ),
    ]
