# Generated by Django 4.1.7 on 2023-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0049_riskreg_riskimpactcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="riskImpactCost",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
