# Generated by Django 4.1.7 on 2023-06-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0050_alter_businessprocess_businessprocesscriticality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="rifha.staff"
            ),
        ),
    ]
