# Generated by Django 4.1.7 on 2023-06-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0050_alter_riskreg_riskimpactcost"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
