# Generated by Django 4.1.7 on 2023-06-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0051_riskreg_residualriskoffset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="riskImpactCost",
            field=models.IntegerField(),
        ),
    ]
