# Generated by Django 4.1.7 on 2023-06-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0052_alter_riskreg_riskimpactcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.IntegerField(),
        ),
    ]
