# Generated by Django 4.1.7 on 2023-06-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0052_remove_businessprocess_businessprocessowner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprocess",
            name="businessProcessOwner",
        ),
        migrations.AddField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.OneToOneField(
                default="1f6cc11f-1337-419b-a3b5-2b4ea7ebea8b",
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.staff",
            ),
            preserve_default=False,
        ),
    ]
