# Generated by Django 4.1.7 on 2023-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0053_alter_riskreg_residualriskoffset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.FloatField(),
        ),
    ]
