# Generated by Django 4.1.7 on 2023-06-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0053_remove_businessprocess_businessprocessowner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_processes",
                to="rifha.staff",
            ),
        ),
    ]
