# Generated by Django 4.1.7 on 2023-06-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0054_alter_riskreg_residualriskoffset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatlikelihood",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
