# Generated by Django 4.1.7 on 2023-06-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0055_alter_riskreg_residualriskoffset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatlikelihood",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
