# Generated by Django 4.1.7 on 2023-06-24 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0055_alter_businessprocess_businessprocessowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.ForeignKey(
                default="3e870b5d-1ab7-4e0b-a5d1-66a2a54c3ad7",
                on_delete=django.db.models.deletion.CASCADE,
                to="rifha.staff",
            ),
        ),
    ]
