# Generated by Django 4.1.7 on 2023-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0056_alter_threatcatalogue_threatlikelihood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatlikelihood",
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
