# Generated by Django 4.1.7 on 2023-06-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0056_alter_businessprocess_businessprocessowner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprocess",
            name="businessProcessOwner",
            field=models.CharField(max_length=36),
        ),
    ]
