# Generated by Django 4.1.7 on 2023-06-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0057_alter_threatcatalogue_threatlikelihood"),
    ]

    operations = [
        migrations.AddField(
            model_name="threatcatalogue",
            name="threatMaxCost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threatcatalogue",
            name="threatMinCost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
