# Generated by Django 4.1.7 on 2023-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0058_threatcatalogue_threatmaxcost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMaxCost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMinCost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatlikelihood",
            field=models.FloatField(),
        ),
    ]
