# Generated by Django 4.1.7 on 2023-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0060_alter_riskreg_residualriskoffset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
