# Generated by Django 4.1.7 on 2023-07-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0061_alter_riskreg_residualriskoffset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMaxCost",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMinCost",
            field=models.FloatField(),
        ),
    ]
