# Generated by Django 4.1.7 on 2023-07-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0062_alter_riskreg_residualriskoffset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riskreg",
            name="riskAssessmentStatus",
            field=models.BooleanField(default=False, verbose_name="Analysis Completed"),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatlikelihood",
            field=models.FloatField(),
        ),
    ]
