# Generated by Django 4.1.7 on 2023-07-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0065_alter_riskreg_riskimpactcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskreg",
            name="residualRiskOffset",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
