# Generated by Django 4.1.7 on 2023-07-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0066_alter_riskreg_residualriskoffset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="riskreg",
            name="riskImpactCost",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
