# Generated by Django 4.1.7 on 2023-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0067_alter_riskreg_riskimpactcost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMaxCost",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="threatcatalogue",
            name="threatMinCost",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
