# Generated by Django 4.1.7 on 2023-07-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rifha", "0072_alter_riskreg_riskasset_alter_riskreg_riskowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprocess",
            name="businessProcessAssets",
            field=models.ManyToManyField(to="rifha.assets"),
        ),
        migrations.AlterField(
            model_name="assets",
            name="assetClassification",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rifha.assetsclassifications",
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="assetOwner",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to="rifha.staff"
            ),
        ),
        migrations.AlterField(
            model_name="assets",
            name="assetType",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="rifha.assetstypes",
            ),
        ),
    ]
