def generate_staff_information():
    first_name_pool = [
        "Jack",
        "Noah",
        "James",
        "Conor",
        "Rían",
        "Liam",
        "Charlie",
        "Daniel",
        "Cillian",
        "Tadhg",
        "Michael",
        "Oisín",
        "Finn",
        "Fionn",
        "Thomas",
        "Seán",
        "Darragh",
        "Luke",
        "Patrick",
        "Harry",
        "Alex",
        "Adam",
        "Cian",
        "Theo",
        "Oliver",
        "Dylan",
        "Jamie",
        "John",
        "Leo",
        "Oscar",
        "Ollie",
        "Ben",
        "Tom",
        "Bobby",
        "Ryan",
        "Tommy",
        "Matthew",
        "Max",
        "Callum",
        "Sam",
        "Danny",
        "Aaron",
        "Alexander",
        "Alfie",
        "Jake",
        "Mason",
        "David",
        "Joseph",
        "Jacob",
        "Ethan",
        "Fiadh",
        "Grace",
        "Emily",
        "Sophie",
        "Éabha",
        "Lucy",
        "Mia",
        "Ava",
        "Lily",
        "Ella",
        "Amelia",
        "Chloe",
        "Hannah",
        "Sophia",
        "Emma",
        "Ellie",
        "Isla",
        "Molly",
        "Olivia",
        "Sadie",
        "Anna",
        "Freya",
        "Evie",
        "Saoirse",
        "Caoimhe",
        "Ruby",
        "Robyn",
        "Kate",
        "Willow",
        "Sofia",
        "Holly",
        "Aoife",
        "Cara",
        "Róisín",
        "Katie",
        "Sadhbh",
        "Leah",
        "Millie",
        "Isabelle",
        "Alice",
        "Clodagh",
        "Zoe",
        "Sarah",
        "Erin",
        "Ada",
        "Annie",
        "Bonnie",
        "Charlotte",
        "Layla",
        "Rosie",
    ]

    surname_pool = [
        " Murphy",
        " Kelly",
        " O’Sullivan",
        " Walsh",
        " Smith",
        " O’Brien",
        " Byrne",
        " Ryan",
        " O’Connor",
        " O’Neill",
        " O’Reilly",
        " Doyle",
        " McCarthy",
        " Gallagher",
        " O’Doherty",
        " Kennedy",
        " Lynch",
        " Murray",
        " Quinn",
        " Moore",
        " McLoughlin",
        " O’Carroll",
        " Connolly",
        " Daly",
        " O’Connell",
        " Wilson",
        " Dunne",
        " Brennan",
        " Burke",
        " Collins",
        " Campbell",
        " Clarke",
        " Johnston",
        " Hughes",
        " O’Farrell",
        " Fitzgerald",
        " Brown",
        " Martin",
        " Maguire",
        " Nolan",
        " Flynn",
        " Thompson",
        " O’Callaghan",
        " O’Donnell",
        " Duffy",
        " O’Mahony",
        " Boyle",
        " Healy",
        " O’Shea",
        " White",
        " Sweeney",
        " Hayes",
        " Kavanagh",
        " Power",
        " McGrath",
        " Moran",
        " Brady",
        " Stewart",
        " Casey",
        " Foley",
        " Fitzpatrick",
        " O’Leary",
        " McDonnell",
        " MacMahon",
        " Donnelly",
        " Regan",
        " Donovan",
        " Burns",
        " Flanagan",
        " Mullan",
        " Barry",
        " Kane",
        " Robinson",
        " Cunningham",
        " Griffin",
        " Kenny",
        " Sheehan",
        " Ward",
        " Whelan",
        " Lyons",
        " Reid",
        " Graham",
        " Higgins",
        " Cullen",
        " Keane",
        " King",
        " Maher",
        " MacKenna",
        " Bell",
        " Scott",
        " Hogan",
        " O’Keeffe",
        " Magee",
        " MacNamara",
        " MacDonald",
        " MacDermott",
        " Molony",
        " O’Rourke",
        " Buckley",
        " O’Dwyer",
    ]

    generate_staff_information
