# Generated by Django 4.1.7 on 2023-03-13 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_trainingcorpus"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="trainingCorpus",
            new_name="trainingCorpus1",
        ),
    ]
