# Generated by Django 4.1.7 on 2023-03-13 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0003_rename_trainingcorpus_trainingcorpus1"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="trainingCorpus1",
            new_name="trainingCorpus",
        ),
    ]
