# Generated by Django 4.1.7 on 2023-03-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0005_rename_trainingcorpus_trainingcorpusdjango"),
    ]

    operations = [
        migrations.CreateModel(
            name="brian",
            fields=[
                ("entryId", models.IntegerField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=45)),
                ("publishedDate", models.DateField()),
                ("dateAdded", models.DateField()),
                ("link", models.TextField()),
                ("text", models.TextField()),
                ("linkHash", models.CharField(max_length=256)),
                ("included", models.IntegerField(default=1)),
                ("classification", models.CharField(max_length=255)),
                ("verisCompatible", models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name="trainingCorpusDjango",
        ),
    ]
