# Generated by Django 4.1.7 on 2023-03-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0007_trainingcorpus_delete_brian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="verisCompatible",
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
