# Generated by Django 4.1.7 on 2023-03-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0008_alter_trainingcorpus_veriscompatible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="classification",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trainingcorpus",
            name="verisCompatible",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
