# Generated by Django 4.1.7 on 2023-03-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0009_alter_trainingcorpus_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="linkHash",
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
