# Generated by Django 4.1.7 on 2023-03-15 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0010_alter_trainingcorpus_linkhash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="entryId",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
