# Generated by Django 4.1.7 on 2023-03-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0015_alter_trainingcorpus_entryid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="linkHash",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
