# Generated by Django 4.1.7 on 2023-03-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0018_alter_trainingcorpus_entryid"),
    ]

    operations = [
        migrations.CreateModel(
            name="textLabels",
            fields=[
                ("entryId", models.BigAutoField(primary_key=True, serialize=False)),
                ("label", models.TextField()),
            ],
        ),
    ]
