# Generated by Django 4.1.7 on 2023-03-19 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0020_trainingcorpus_textlabel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingcorpus",
            name="classification",
        ),
    ]
