# Generated by Django 4.1.7 on 2023-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0021_remove_trainingcorpus_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcorpus",
            name="classificationText",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
