# Generated by Django 4.1.7 on 2023-03-19 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0024_remove_trainingcorpus_textlabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingcorpus",
            name="textLabel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.textlabels",
            ),
        ),
    ]
