# Generated by Django 4.1.7 on 2023-03-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0025_trainingcorpus_textlabel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="textlabels",
            name="label",
            field=models.TextField(max_length=200),
        ),
    ]
