# Generated by Django 4.1.7 on 2023-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0026_alter_textlabels_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="textlabels",
            name="modelAssociated",
            field=models.IntegerField(default=1),
        ),
    ]
