# Generated by Django 4.1.7 on 2023-03-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0026_alter_textlabels_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingcorpus",
            name="linkHash",
            field=models.UUIDField(db_index=True, unique=True),
        ),
    ]
