# Generated by Django 4.1.7 on 2023-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0029_alter_textlabels_modelassociated"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_incident_details",
            fields=[
                (
                    "incident_id",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("security_incident", models.CharField(max_length=45)),
                ("source_id", models.CharField(max_length=45)),
                ("analysis_status", models.CharField(max_length=200)),
                ("created", models.DateTimeField()),
                ("master_id", models.CharField(max_length=45)),
                ("modified", models.DateTimeField()),
            ],
        ),
    ]
