# Generated by Django 4.1.7 on 2023-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0030_veris_incident_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="errorCapture",
            fields=[
                ("incident_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("error", models.TextField()),
                ("script", models.CharField(max_length=200)),
                ("line", models.TextField(max_length=5)),
            ],
        ),
    ]
