# Generated by Django 4.1.7 on 2023-04-22 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0032_delete_errorcapture"),
    ]

    operations = [
        migrations.CreateModel(
            name="errorCapture",
            fields=[
                ("incident_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("execution_type", models.TextField(blank=True)),
                ("execution_object", models.CharField(max_length=250)),
                ("file_name", models.CharField(max_length=250)),
                ("file_line", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2023, 4, 22, 17, 53, 47, 630731),
                    ),
                ),
            ],
        ),
    ]
