# Generated by Django 4.1.7 on 2023-04-22 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0033_errorcapture"),
    ]

    operations = [
        migrations.AddField(
            model_name="veris_incident_details",
            name="summary",
            field=models.TextField(default="None"),
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 22, 18, 14, 40, 704661)
            ),
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="file_line",
            field=models.IntegerField(blank=True),
        ),
    ]
