# Generated by Django 4.1.7 on 2023-04-23 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0034_veris_incident_details_summary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 23, 9, 0, 48, 995607)
            ),
        ),
        migrations.AlterField(
            model_name="veris_incident_details",
            name="created",
            field=models.DateField(),
        ),
    ]
