# Generated by Django 4.1.7 on 2023-04-23 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0035_alter_errorcapture_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_incident_action_details",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("action", models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 23, 17, 31, 40, 491569)
            ),
        ),
    ]
