# Generated by Django 4.1.7 on 2023-04-26 20:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0039_alter_errorcapture_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="web_scraper_log",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source", models.CharField(max_length=45)),
                ("article_count", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime(2023, 4, 26, 21, 20, 38, 134097)
            ),
        ),
    ]
