# Generated by Django 4.1.7 on 2023-04-27 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0040_web_scraper_log_alter_errorcapture_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 27, 21, 34, 43, 919735)
            ),
        ),
    ]
