# Generated by Django 4.1.7 on 2023-04-27 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0041_alter_errorcapture_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="web_scraper_log",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 27, 21, 53, 19, 918050)
            ),
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 4, 27, 21, 53, 19, 917946)
            ),
        ),
    ]
