# Generated by Django 4.1.7 on 2023-04-28 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0042_web_scraper_log_date_alter_errorcapture_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 28, 9, 51, 28, 573004)
            ),
        ),
        migrations.AlterField(
            model_name="web_scraper_log",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 28, 9, 51, 28, 573116)
            ),
        ),
    ]
