# Generated by Django 4.1.7 on 2023-05-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0046_alter_errorcapture_execution_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_details",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("action", models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name="errorcapture",
            name="date",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="web_scraper_log",
            name="date",
            field=models.DateField(blank=True),
        ),
    ]
