# Generated by Django 4.1.7 on 2023-05-06 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0052_veris_action_malware_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_actor_details",
            fields=[
                ("vat_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("actor_type", models.CharField(max_length=45)),
                ("region", models.CharField(max_length=45)),
                ("industry", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_actor_variety",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("result", models.CharField(max_length=200)),
                (
                    "vat_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_actor_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_actor_origin",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("result", models.CharField(max_length=200)),
                (
                    "vat_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_actor_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_actor_notes",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("notes", models.CharField(max_length=200)),
                (
                    "vat_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_actor_details",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_actor_motive",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("result", models.CharField(max_length=200)),
                (
                    "vat_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_actor_details",
                    ),
                ),
            ],
        ),
    ]
