# Generated by Django 4.1.7 on 2023-05-07 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0054_rename_result_veris_action_actor_motive_motive_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="veris_actor_details",
            new_name="veris_action_actor_details",
        ),
    ]
