# Generated by Django 4.1.7 on 2023-05-07 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0055_rename_veris_actor_details_veris_action_actor_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veris_action_actor_details",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="veris_action_actor_details",
            name="region",
        ),
    ]
