# Generated by Django 4.1.7 on 2023-05-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0059_alter_veris_action_hacking_results_vah_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_social",
            fields=[
                ("vas_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("cve", models.CharField(max_length=200)),
                ("notes", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="veris_action_hacking_results",
            name="vah_Id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.veris_action_social",
            ),
        ),
        migrations.AlterField(
            model_name="veris_action_hacking_variety",
            name="vah_Id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.veris_action_social",
            ),
        ),
        migrations.AlterField(
            model_name="veris_action_hacking_vector",
            name="vah_Id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="polls.veris_action_social",
            ),
        ),
    ]
