# Generated by Django 4.1.7 on 2023-05-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0061_rename_vah_id_veris_action_hacking_results_vas_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_hacking_target",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target", models.CharField(max_length=1000)),
                (
                    "vas_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_social",
                    ),
                ),
            ],
        ),
    ]
