# Generated by Django 4.1.7 on 2023-05-07 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "polls",
            "0063_rename_veris_action_hacking_target_veris_action_social_results_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veris_action_social",
            name="cve",
        ),
    ]
