# Generated by Django 4.1.7 on 2023-05-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0065_veris_action_misuse_veris_action_misuse_vector_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_misuse_target",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("target", models.CharField(max_length=1000)),
                (
                    "vamis_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_misuse",
                    ),
                ),
            ],
        ),
    ]
