# Generated by Django 4.1.7 on 2023-05-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0066_veris_action_misuse_target"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_physical",
            fields=[
                ("vamis_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("notes", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_physical_vector",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vector", models.CharField(max_length=200)),
                (
                    "vamis_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_physical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_physical_variety",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("variety", models.CharField(max_length=200)),
                (
                    "vamis_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_physical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_physical_location",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("results", models.CharField(max_length=1000)),
                (
                    "vamis_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_physical",
                    ),
                ),
            ],
        ),
    ]
