# Generated by Django 4.1.7 on 2023-05-07 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0067_veris_action_physical_veris_action_physical_vector_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veris_action_physical",
            old_name="vamis_Id",
            new_name="vap_Id",
        ),
        migrations.RenameField(
            model_name="veris_action_physical_location",
            old_name="results",
            new_name="location",
        ),
        migrations.RenameField(
            model_name="veris_action_physical_location",
            old_name="vamis_Id",
            new_name="vap_Id",
        ),
        migrations.RenameField(
            model_name="veris_action_physical_variety",
            old_name="vamis_Id",
            new_name="vap_Id",
        ),
        migrations.RenameField(
            model_name="veris_action_physical_vector",
            old_name="vamis_Id",
            new_name="vap_Id",
        ),
    ]
