# Generated by Django 4.1.7 on 2023-05-07 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0069_veris_action_physical_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_action_error",
            fields=[
                ("vae_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("notes", models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_error_vector",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("vector", models.CharField(max_length=200)),
                (
                    "vae_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_error",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_action_error_variety",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("variety", models.CharField(max_length=200)),
                (
                    "vae_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_action_error",
                    ),
                ),
            ],
        ),
    ]
