# Generated by Django 4.1.7 on 2023-05-07 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0075_rename_veris_action_actor_details_veris_actor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_asset",
            fields=[
                ("vass_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("notes", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_variety",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("variety", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_ownership",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ownership", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_management",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("management", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_hosting",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("hosting", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_cloud",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("cloud", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_asset_accessibility",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("accessibility", models.CharField(max_length=200)),
                (
                    "vass_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
    ]
