# Generated by Django 4.1.7 on 2023-05-08 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0077_alter_veris_asset_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="veris_impact",
            fields=[
                ("vim_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("incident_id", models.CharField(max_length=45)),
                ("iso_currency_code", models.CharField(max_length=5)),
                ("overall_amount", models.IntegerField(max_length=10)),
                ("overall_min_amount", models.IntegerField(max_length=10)),
                ("overall_max_amount", models.IntegerField(max_length=10)),
                ("notes", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="veris_impact_overall_rating",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("overall_rating", models.CharField(max_length=200)),
                (
                    "vim_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="veris_impact_loss",
            fields=[
                ("entry_Id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.CharField(max_length=50)),
                ("variety", models.CharField(max_length=50)),
                ("overall_amount", models.IntegerField(max_length=10)),
                ("min_amount", models.IntegerField(max_length=10)),
                ("max_amount", models.IntegerField(max_length=10)),
                (
                    "vim_Id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.veris_asset",
                    ),
                ),
            ],
        ),
    ]
