# Generated by Django 4.1.7 on 2023-05-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0079_alter_veris_impact_overall_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="veris_impact",
            name="overall_rating",
            field=models.CharField(default="None", max_length=45),
        ),
        migrations.DeleteModel(
            name="veris_impact_overall_rating",
        ),
    ]
