# Generated by Django 4.1.7 on 2023-05-08 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0080_veris_impact_overall_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="veris_impact_loss",
            old_name="rating",
            new_name="entry",
        ),
        migrations.RenameField(
            model_name="veris_impact_loss",
            old_name="variety",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="veris_impact_loss",
            name="max_amount",
        ),
        migrations.RemoveField(
            model_name="veris_impact_loss",
            name="min_amount",
        ),
        migrations.RemoveField(
            model_name="veris_impact_loss",
            name="overall_amount",
        ),
    ]
