# Generated by Django 4.1.7 on 2023-06-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0081_rename_rating_veris_impact_loss_entry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="interviewQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interviewee_Id", models.UUIDField()),
                ("question_1", models.TextField()),
                ("question_2", models.TextField()),
                ("question_3", models.TextField()),
                ("question_4", models.TextField()),
                ("question_5", models.TextField()),
                ("question_6", models.TextField()),
                ("question_7", models.TextField()),
                ("question_8", models.TextField()),
                ("question_9", models.TextField()),
                ("question_10", models.TextField()),
                ("date_created", models.DateField(auto_now=True)),
            ],
        ),
    ]
