# Generated by Django 4.1.7 on 2023-06-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0082_interviewquestions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewquestions",
            name="interviewee_Id",
            field=models.CharField(max_length=100),
        ),
    ]
