# Generated by Django 4.1.7 on 2023-06-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0083_alter_interviewquestions_interviewee_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="interviewee",
            fields=[
                (
                    "interviewee_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("interviewee_reference", models.UUIDField()),
                ("interviewee_role", models.CharField(max_length=250)),
                ("interviewee_fte", models.IntegerField()),
                ("interviewee_org_type", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="researchQuestion",
            fields=[
                ("question_id", models.IntegerField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="intervieweeResponse",
            fields=[
                ("answer_id", models.IntegerField(primary_key=True, serialize=False)),
                ("answer_text", models.TextField()),
                ("positivity_score", models.FloatField()),
                ("neutrality_score", models.FloatField()),
                ("negativity_score", models.FloatField()),
                (
                    "interviewee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.interviewee",
                    ),
                ),
                (
                    "question_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polls.researchquestion",
                    ),
                ),
            ],
        ),
    ]
