# Generated by Django 4.1.7 on 2023-06-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0084_interviewee_researchquestion_intervieweeresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewee",
            name="interviewee_id",
            field=models.IntegerField(
                auto_created=True, primary_key=True, serialize=False
            ),
        ),
    ]
