# Generated by Django 4.1.7 on 2023-06-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0088_alter_researchquestion_question_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervieweeresponse",
            name="compound_score",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
