# Generated by Django 4.1.7 on 2023-07-23 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0090_remove_intervieweeresponse_interviewee_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervieweeresponse",
            name="interviewee_id",
        ),
        migrations.AddField(
            model_name="intervieweeresponse",
            name="interviewee_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="polls.interviewee",
            ),
        ),
    ]
