# Generated by Django 4.1.7 on 2023-07-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0091_remove_intervieweeresponse_interviewee_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intervieweeresponse",
            old_name="answer_id",
            new_name="response_id",
        ),
        migrations.RemoveField(
            model_name="intervieweeresponse",
            name="interviewee_id",
        ),
        migrations.AddField(
            model_name="intervieweeresponse",
            name="interviewee_id",
            field=models.ManyToManyField(to="polls.interviewee"),
        ),
    ]
