# Generated by Django 4.1.7 on 2023-07-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0092_rename_answer_id_intervieweeresponse_response_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="intervieweeresponse",
            old_name="answer_text",
            new_name="primary_answer_text",
        ),
        migrations.AddField(
            model_name="intervieweeresponse",
            name="secondary_answer_text",
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
    ]
