# Generated by Django 4.1.7 on 2023-07-23 21:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "polls",
            "0093_rename_answer_text_intervieweeresponse_primary_answer_text_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="interviewQuestions",
        ),
    ]
