# Generated by Django 4.1.7 on 2023-07-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0094_delete_interviewquestions"),
    ]

    operations = [
       
        migrations.AddField(
            model_name="intervieweeresponse",
            name="interviewee_id",
            field=models.CharField(default=None, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="intervieweeresponse",
            name="question_id",
            field=models.CharField(default="None", max_length=36),
            preserve_default=False,
        ),
    ]
