# Generated by Django 4.1.7 on 2023-07-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0095_remove_intervieweeresponse_interviewee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervieweeresponse",
            name="interviewee_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="intervieweeresponse",
            name="question_id",
            field=models.IntegerField(default=1),
        ),
    ]
