# Generated by Django 4.1.7 on 2023-07-24 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0096_alter_intervieweeresponse_interviewee_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="intervieweeResponse",
        ),
    ]
