# Generated by Django 4.1.7 on 2023-07-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0098_transcriptcapture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transcriptcapture",
            name="interviewee_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="polls.interviewee"
            ),
        ),
    ]
